spring:
  application:
    name: springboot-gradle-zuul
  data:
    mongodb:
      database: testdb
      host: 192.168.0.92
      port: 27017
      
server:
  port: 8080


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0



zuul:
  sensitive-headers:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    a-api:
      path: /api/products/**
      url: http://localhost:8081
      stripPrefix: false
    b-api:
      path: /bars/**
      url: http://localhost:8082
      stripPrefix: false
  ribbon:
    eager-load:
      enabled: false
      

